# Generated by Django 4.1.7 on 2023-02-28 13:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=13)),
                ('type', models.CharField(choices=[('BS', 'Bakalavr'), ('MS', 'Magistr')], default='BS', max_length=2)),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('received_money', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.university')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
