# Generated by Django 4.1.7 on 2023-02-28 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['name'], 'verbose_name': 'university', 'verbose_name_plural': 'universities'},
        ),
    ]
