# Generated by Django 4.1.7 on 2023-02-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=15)),
                ('total_money', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_type', models.CharField(choices=[('CASH', 'Naqd pul'), ('TRANS', "Pul o'tkazmalari")], default='TRANS', max_length=8)),
                ('type', models.CharField(choices=[('JIS', 'Jismoniy shaxs'), ('YUR', 'Yuridik shaxs')], default='JIS', max_length=8)),
                ('status', models.CharField(choices=[('NEW', 'Yangi'), ('MOD', 'Moderatsiyada'), ('CNF', 'Tasdiqlangan'), ('CNC', 'Bekor qilingan')], default='NEW', max_length=8)),
                ('organization', models.CharField(max_length=128)),
            ],
        ),
    ]
