# Generated by Django 4.1.7 on 2023-02-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_alter_sponsor_options_sponsor_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
    ]
