# Generated by Django 4.1.7 on 2023-02-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0003_alter_sponsor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='organization',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
