# Generated by Django 4.1.7 on 2023-02-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0004_alter_sponsor_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='balance',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='spent_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
