# Generated by Django 4.1.7 on 2023-03-01 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sponsors', '0005_remove_sponsor_balance_sponsor_spent_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='sponsors.sponsor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='sponsors.sponsor')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
