# Generated by Django 4.1.7 on 2023-03-01 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_received_money'),
        ('sponsorships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='students.student'),
        ),
    ]
